services:
  node:
    container_name: react-suspense-container
    image: react-suspense-image
    # restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
